// Shared access to /data/registry.json — generated by scripts/generate-datasets.mjs
// from registry/datasets.yml (the declarative source of truth).

let cache = null

export function loadRegistry() {
  if (!cache) {
    cache = fetch('/data/registry.json').then(r => r.json())
  }
  return cache
}

export function rightsMeta(rights) {
  switch (rights) {
    case 'full':
      return { label: 'Full text', tone: 'pine' }
    case 'title-only':
      return { label: 'Index only', tone: 'oxblood' }
    default:
      return { label: rights, tone: 'ink' }
  }
}

export function statusMeta(status) {
  switch (status) {
    case 'published':
      return { label: 'Published', tone: 'pine' }
    case 'raw':
      return { label: 'Source acquired — extraction in progress', tone: 'brass' }
    case 'reference':
      return { label: 'Reference dataset', tone: 'moss' }
    default:
      return { label: status, tone: 'ink' }
  }
}
